package pkg203lab2;

/**
 *
 * @author wihousen
 */
public class GreeterApp {

    public static void main(String[] args) {

        /**
         * Greeter construct for making a greeter object, with a string as input
         */
        Greeter worldGreeter = new Greeter("World & Wilson");

        Greeter variGreeter = new Greeter("uselessString!");

        /**
         * calling setName method on worldGreeter to change the string
         */
        worldGreeter.setName("Mike&Alex");

        Greeter Greeter2 = variGreeter;
        Greeter Greeter3 = variGreeter;

        Greeter2.setName("Awesome Coaches");
        Greeter3.sayHello();

        Greeter2.swapNames(Greeter3);

        /**
         * making a string with the word greeter object
         */
        String greeting = worldGreeter.sayHello();
        String greeting2 = variGreeter.sayHello();

        /**
         * printing the greeting generated by greeting
         */
        System.out.println(greeting);
        System.out.println(greeting2);

    }
}
